Changed the label, translate everything into English

diff --git a/.github/workflows/controllo_link.yml b/.github/workflows/controllo_link.yml
--- a/.github/workflows/controllo_link.yml
+++ b/.github/workflows/controllo_link.yml
@@ -23,26 +23,26 @@ jobs:
       
     - name: Run Broken Links Checker
       run: |
-        # Dividi la lista di link in un array separato da virgola
+        # Split the list of links into an array separated by commas
         IFS=',' read -ra LINKS <<< "$WEBSITE_URL"
         BROKEN_LINKS=""
-
-        # Scansiona i link e verifica se sono raggiungibili
+        
+        # Scan the links and verify if they are reachable
         for link in "${LINKS[@]}"; do
           if [[ $link =~ ^(http|https):// ]]; then
-            # Se il link inizia con "http://" o "https://", verifica se è raggiungibile
+            # If the link starts with "http://" or "https://", check if it is reachable
             if ! curl -IsSk "$link" > /dev/null; then
               BROKEN_LINKS="$BROKEN_LINKS,$link"
             fi
           fi
         done
 
-          # Rimuovi la virgola iniziale se ci sono link non raggiungibili
+        # Remove the initial comma if there are unreachable links
         if [ -n "$BROKEN_LINKS" ]; then
           BROKEN_LINKS=$(echo "$BROKEN_LINKS" | cut -c 2-)
           echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV
-          echo "Broken links found: $BROKEN_LINKS"
-          echo "Broken links found, failing the workflow"
+          echo "Broken links found: $BROKEN_LINKS" >&2
+          echo "Broken links found, failing the workflow" >&2
           exit 1
         else
           echo "No broken links found"
