Update controllo_link.yml

diff --git a/.github/workflows/controllo_link.yml b/.github/workflows/controllo_link.yml
--- a/.github/workflows/controllo_link.yml
+++ b/.github/workflows/controllo_link.yml
@@ -22,9 +22,13 @@ jobs:
        echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
       
     - name: Run Broken Links Checker
-      run: | 
-       npx broken-link-checker@latest $WEBSITE_URL --ordered --recursive --filter-level error 
-       
+      run: |
+        BROKEN_LINKS=$(npx broken-link-checker@latest $WEBSITE_URL --ordered --recursive --filter-level error)
+        echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV
+        if [ -n "$BROKEN_LINKS" ]; then
+          echo "Broken links found, failing the workflow"
+          exit 1
+        fi
 
     - uses: actions/checkout@v3
       if: failure()
